### ISSUE TITLE
Add ooaofooa schema for BridgePoint 7

### ISSUE THREAD

**Issue by johnrwolfe** [xtuml/pyxtuml#31]
Most users have migrated from BridgePoint 6 to BridgePoint 7, and the latter relies on an updated ooaofooa schema.

**Comment by john-tornblom** [comment]
There is a script to generate the schema from a bridgepoint metamodel at: 
    https://github.com/xtuml/pyxtuml/blob/master/bridgepoint/gen_pyxtuml_schema.py

**Comment by john-tornblom** [comment]
@leviathan747, @keithbrown and @cortlandstarrett, since you are more involved with the planning of metamodel changes, could one of you submit a PR for this issue after an appropriate bridgepoint release?

**Comment by cortlandstarrett** [comment]
@leviathan747 or I will do this sometime in the next month or so.

**Comment by leviathan747** [comment]
@cortlandstarrett @john-tornblom @johnrwolfe #32 has been opened to address this. Cort, I put you as a reviewer since you are the most familiar with the schema changes in the last year, you can review that change set and make sure nothing is surprising to you.

This has been tested with the Ciera model compiler and appears to be working as expected. I also ran the pyxtuml test suite locally with python 3 and python 2 (are you still bothering to test with python 2?). There were many schema mismatch warnings so maybe the test data needs to be updated, but they all passed.

**Comment by john-tornblom** [comment]
This is addressed by 15bbff82edc3069, closing.
